### PR TITLE
color_theme

### PR DESCRIPTION
**Pull request by Ramlanisagar**
#1 
added a color picker which will directly change color of background.
theme_1
theme_2
theme_3

### CODE REVIEW

**Comment by programmerraja** [comment]
@Ramlanisagar 
I know you spent your valuable time on our project 
but i am extremely sorry we are not interested in adding color theme to our app .

Keep contributing✌️

**Comment by Ramlanisagar** [comment]
@programmerraja please let me know what changes I can do because I had spent more time on this project so it will be easy for me to do changes.

**Comment by Ramlanisagar** [comment]
@programmerraja if you don't want to merge than it's totally your choice but can you please add label hacktober-accepted to my PR so that it will be counted as a valid PR for hacktober fest.

**Comment by Ramlanisagar** [comment]
Thanks @programmerraja

**Pull request closed without merging**
